name: Build &amp; Obfuscate Plugin
on:
  push:
    tags:
      - '*.*.*.*'
jobs:
  Build:
    permissions:
      contents: write
    runs-on: windows-latest
    env:
      REPO_NAME: ${{ github.repository }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get Environment Variables
        run: |
          $tag = "${{ github.ref }}" -replace 'refs/tags/', ''
          "tag=$tag" | Out-File -Append -FilePath $Env:GITHUB_ENV

      - name: Prepare signing key
        run: echo "${{ secrets.PFR_SIGNING_PRIVATE_PEM }}" > signing_key.pem

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Download Dalamud Latest
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

      - name: Restore Nuget Packages
        run: dotnet restore PartyFinderReborn/PartyFinderReborn.csproj
        
      - name: Inject private key into Constants.cs
        run: .\scripts\inject-key.ps1 -PrivateKeyPath "signing_key.pem" -ConstantsFilePath "PartyFinderReborn\Constants.cs"

      - name: Build Plugin
        run: dotnet build --no-restore -c Release PartyFinderReborn/PartyFinderReborn.csproj -p:AssemblyVersion=${{ env.tag }} -p:FileVersion=${{ env.tag }} -p:PackageVersion=${{ env.tag }} -p:InformationalVersion=${{ env.tag }} -p:DefineConstants="RELEASE_BUILD" --output .\build

      - name: Setup ConfuserEx
        run: |
          # Download and setup ConfuserEx CLI
          Invoke-WebRequest -Uri https://github.com/mkaring/ConfuserEx/releases/latest/download/ConfuserEx-CLI.zip -OutFile ConfuserEx-CLI.zip
          Expand-Archive -Force ConfuserEx-CLI.zip -DestinationPath confuserex

      - name: Obfuscate Plugin
        run: |
          # Create directory structure for ConfuserEx
          New-Item -ItemType Directory -Path ".\PartyFinderReborn\bin\Release" -Force
          # Copy built DLL to expected location for ConfuserEx
          Copy-Item ".\build\PartyFinderReborn.dll" ".\PartyFinderReborn\bin\Release\PartyFinderReborn.dll" -Force
          
          # Copy all dependencies for ConfuserEx resolution
          # Copy Dalamud assemblies from the dev installation
          $dalamudPath = "$env:AppData\XIVLauncher\addon\Hooks\dev"
          if (Test-Path "$dalamudPath\Dalamud.dll") {
            Copy-Item "$dalamudPath\*.dll" ".\PartyFinderReborn\bin\Release\" -Force -ErrorAction SilentlyContinue
          }
          
          # Copy NuGet package dependencies from build output
          if (Test-Path ".\build\*.dll") {
            Get-ChildItem ".\build\*.dll" | Where-Object { $_.Name -ne "PartyFinderReborn.dll" } | Copy-Item -Destination ".\PartyFinderReborn\bin\Release\" -Force
          }
          
          # Run obfuscation
          .\confuserex\Confuser.CLI.exe -n ConfuserEx_Minimum.crproj

      - name: Prepare Release Files
        run: |
          # Copy obfuscated DLL back to build directory
          Copy-Item ".\Confused\PartyFinderReborn.dll" ".\build\PartyFinderReborn.dll" -Force
          # Copy plugin manifest
          Copy-Item ".\PartyFinderReborn\PartyFinderReborn.json" ".\build\PartyFinderReborn.json" -Force

      - name: Zip Plugin
        run: Compress-Archive -Path .\build\* -DestinationPath .\build\PartyFinderReborn.zip

      - name: Publish Plugin
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/PartyFinderReborn.zip
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up signing key
        if: always()
        run: Remove-Item -Path signing_key.pem -Force -ErrorAction SilentlyContinue
